[package]
name = "rustyrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10.0"
diesel = { version = "2.0.2", features = ["mysql"] }
dotenvy = "0.15.6"